[package]
name = "magiskpolicy"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["staticlib", "rlib"]
path = "lib.rs"

[build-dependencies]
cxx-gen = { workspace = true }

[features]
no-main = []

[dependencies]
base = { workspace = true }
cxx = { workspace = true }
