[workspace]
exclude = ["external"]
members = ["base", "boot", "core", "init", "sepolicy"]

[workspace.dependencies]
cxx = { path = "external/cxx-rs" }
cxx-gen = { path = "external/cxx-rs/gen/lib" }
libc = "0.2"
cfg-if = "1.0"
anyhow = "1.0"
num-traits = "0.2"
num-derive = "0.3"
thiserror = "1.0"
protobuf = "3.2.0"
protobuf-codegen = "3.2.0"
byteorder = "1"
size = "0.4"
clap = "4.3"

[profile.dev]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
